### ISSUE TITLE
Get specific element from body example

### ISSUE THREAD

**Issue by Joostul** [Azure/api-management-samples#15]
Your policy examples are great, but is it also possible to get for example a specific element from the body of a request? I see examples for Methods and Variables, but not of the body. Could you provide an example?

**Comment by Joostul** [comment]
I have since found a way so I thought I'd share. There are probably easier ways to do this.

`context.Request.Body.As<JObject>(preserveContent: true).GetValue("Envelope").Value<JObject>("Body").Value<JObject>("<YourElementName>").Value<string>("<YourAttributeName>")`

**Comment by Ash-Mishra** [comment]
How does we handle if in case "YourElementName" is not present in the body?

**Comment by Tenseiga** [comment]
> How does we handle if in case "YourElementName" is not present in the body?

u can use choose - when block to check if the element contains..
